POST http://localhost:5000/authentication/changePassword HTTP/1.1
Content-Type: application/json

{
    "newPassword": "123",
    "currentPassword": "anmol"
}

###
GET http://localhost:5000/order/selected-customer/61c85262405ec62a4f404505 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWMxYmE1M2MwNzRlM2Q4MmNjY2EzYTIiLCJuYW1lIjoiT3duZXIiLCJpYXQiOjE2NDA1MTUwNDEsImV4cCI6MTY0MDYwMTQ0MX0.VUg5j1z9LyzUuMXIFO4Z99KIStXntoG5uOt88rbiQss